name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "Python/config.json"
        FILE_DATA: ${CONFIG}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag discord-classroom-bot:latest --tag discord-classroom-bot:$(date +%s)
        docker run --name discord-classroom-bot -d -i -t discord-classroom-bot
        docker exec discord-classroom-bot pytest Testing/utils_unit_testing.py
